// ====================================================================
// GAME CONTENT — LovePlay Phase 1
// All content is Play Store safe: romantic, suggestive, never explicit.
// Categories: Cute, Romantic, Bold (Premium), Deep
// Total: ~485 cards
// ====================================================================

export interface GameCard {
    id: string;
    text: string;
    type?: "truth" | "dare";
    category?: string;
    isPremium?: boolean;
}

// ──────────────────────────────────────────────
// 1. TRUTH OR DARE (240 cards)
// ──────────────────────────────────────────────

export const truthOrDare = {
    // ─── CUTE (50 cards) ───
    cute: [
        { id: "tc1", text: "What's the first thing you noticed about me?", type: "truth" },
        { id: "tc2", text: "What song reminds you of us?", type: "truth" },
        { id: "tc3", text: "What's your favorite memory of us together?", type: "truth" },
        { id: "tc4", text: "If we were a movie couple, who would we be?", type: "truth" },
        { id: "tc5", text: "What's the cutest thing I do without realizing it?", type: "truth" },
        { id: "tc6", text: "What's your favorite pet name you've ever called me?", type: "truth" },
        { id: "tc7", text: "What outfit of mine do you love the most?", type: "truth" },
        { id: "tc8", text: "What's something small I do that makes your day?", type: "truth" },
        { id: "tc9", text: "When did you first realize you liked me?", type: "truth" },
        { id: "tc10", text: "What emoji best describes our relationship?", type: "truth" },
        { id: "tc11", text: "What was your first impression of me?", type: "truth" },
        { id: "tc12", text: "What's one small thing I do that secretly makes you smile?", type: "truth" },
        { id: "tc13", text: "If we had a theme song, what would it be?", type: "truth" },
        { id: "tc14", text: "When did you realize you liked me more than a friend?", type: "truth" },
        { id: "tc15", text: "What's your favorite thing we do together on lazy days?", type: "truth" },
        { id: "tc16", text: "What's a silly habit of mine that you secretly find adorable?", type: "truth" },
        { id: "tc17", text: "If you could describe our relationship in a movie genre, what would it be?", type: "truth" },
        { id: "tc18", text: "What's the funniest thing that's happened to us as a couple?", type: "truth" },
        { id: "tc19", text: "What's a food that always reminds you of me?", type: "truth" },
        { id: "tc20", text: "If we had matching tattoos, what would they be?", type: "truth" },
        { id: "tc21", text: "What's the most random thing you love about me?", type: "truth" },
        { id: "tc22", text: "What's one thing I do that always makes you laugh?", type: "truth" },
        { id: "tc23", text: "What's a place that feels like 'ours'?", type: "truth" },
        { id: "tc24", text: "If we had a couple superpower, what would it be?", type: "truth" },
        { id: "tc25", text: "What's a dream you've had about us that made you smile?", type: "truth" },
        { id: "dc1", text: "Give me a forehead kiss right now 💋", type: "dare" },
        { id: "dc2", text: "Send me the cutest selfie on your phone", type: "dare" },
        { id: "dc3", text: "Write a short love note on a piece of paper for me", type: "dare" },
        { id: "dc4", text: "Slow dance with me for 30 seconds — no music", type: "dare" },
        { id: "dc5", text: "Tell me three things you love about me while holding my hand", type: "dare" },
        { id: "dc6", text: "Do your best impression of how I laugh", type: "dare" },
        { id: "dc7", text: "Recreate our first photo together", type: "dare" },
        { id: "dc8", text: "Draw a portrait of me in 60 seconds", type: "dare" },
        { id: "dc9", text: "Call me by a brand new cute nickname for the rest of the night", type: "dare" },
        { id: "dc10", text: "Hug me for a full 20 seconds without letting go", type: "dare" },
        { id: "dc11", text: "Hold my hand and don't let go for one full minute.", type: "dare" },
        { id: "dc12", text: "Give me your best dramatic movie-style compliment.", type: "dare" },
        { id: "dc13", text: "Recreate the way we first said hello.", type: "dare" },
        { id: "dc14", text: "Make up a silly handshake just for us right now", type: "dare" },
        { id: "dc15", text: "Send me a voice message saying you love me in the silliest way", type: "dare" },
        { id: "dc16", text: "Do your best impression of me ordering food", type: "dare" },
        { id: "dc17", text: "Write a 3-word love message on my palm with your finger", type: "dare" },
        { id: "dc18", text: "Take a goofy couple selfie and make it your lockscreen", type: "dare" },
        { id: "dc19", text: "Give me a piggyback ride (or try to!)", type: "dare" },
        { id: "dc20", text: "Act out how we'd meet if we were in a rom-com", type: "dare" },
        { id: "dc21", text: "Sing our favorite song to me — badly and proudly", type: "dare" },
        { id: "dc22", text: "Stack your hands on mine and don't break eye contact for 30 seconds", type: "dare" },
        { id: "dc23", text: "Tell me your favorite thing about today in a dramatic voice", type: "dare" },
        { id: "dc24", text: "Make up a 4-line poem about us on the spot", type: "dare" },
        { id: "dc25", text: "Give me a compliment you'd write on a greeting card", type: "dare" },
    ] as GameCard[],

    // ─── ROMANTIC (50 cards) ───
    romantic: [
        { id: "tr1", text: "What's the most romantic moment we've shared?", type: "truth" },
        { id: "tr2", text: "Where would you take me on our dream vacation?", type: "truth" },
        { id: "tr3", text: "What does love feel like to you?", type: "truth" },
        { id: "tr4", text: "What's one romantic gesture you've always wanted to do for me?", type: "truth" },
        { id: "tr5", text: "What's a love song that perfectly describes how you feel about me?", type: "truth" },
        { id: "tr6", text: "If you could relive one moment with me, which would it be?", type: "truth" },
        { id: "tr7", text: "What does my presence in your life mean to you?", type: "truth" },
        { id: "tr8", text: "What's the most romantic scene in a movie you'd want us to recreate?", type: "truth" },
        { id: "tr9", text: "When do you feel most loved by me?", type: "truth" },
        { id: "tr10", text: "What future moment with me are you most excited about?", type: "truth" },
        { id: "tr11", text: "Describe your perfect date night with me.", type: "truth" },
        { id: "tr12", text: "What's a memory of us that you replay in your head?", type: "truth" },
        { id: "tr13", text: "What's something romantic you've always wanted to try together?", type: "truth" },
        { id: "tr14", text: "What does love feel like when you're with me?", type: "truth" },
        { id: "tr15", text: "What's a love language you wish you expressed more?", type: "truth" },
        { id: "tr16", text: "If you wrote a love letter to me right now, what would the first line be?", type: "truth" },
        { id: "tr17", text: "What's a small romantic tradition you'd like us to start?", type: "truth" },
        { id: "tr18", text: "When did you first feel truly safe with me?", type: "truth" },
        { id: "tr19", text: "What's your favorite way to show me affection?", type: "truth" },
        { id: "tr20", text: "If our love story was a book, what would the title be?", type: "truth" },
        { id: "tr21", text: "What's a place you want to visit just the two of us?", type: "truth" },
        { id: "tr22", text: "What's a simple moment with me that felt deeply romantic?", type: "truth" },
        { id: "tr23", text: "What's a promise you silently made to me?", type: "truth" },
        { id: "tr24", text: "What's the most romantic text I've ever sent you?", type: "truth" },
        { id: "tr25", text: "What does forever mean to you when you think about us?", type: "truth" },
        { id: "dr1", text: "Look into my eyes for 60 seconds without looking away 👀", type: "dare" },
        { id: "dr2", text: "Whisper something romantic in my ear", type: "dare" },
        { id: "dr3", text: "Plan our perfect date night out loud right now", type: "dare" },
        { id: "dr4", text: "Hold both my hands and say something you've never told me", type: "dare" },
        { id: "dr5", text: "Describe our perfect future home in detail", type: "dare" },
        { id: "dr6", text: "Write me a two-line poem right now", type: "dare" },
        { id: "dr7", text: "Share a voice note saying why you love me", type: "dare" },
        { id: "dr8", text: "Slow dance with me to the next song that plays", type: "dare" },
        { id: "dr9", text: "Give me a butterfly kiss (eyelashes on my cheek)", type: "dare" },
        { id: "dr10", text: "Take a candid photo of me and set it as your wallpaper", type: "dare" },
        { id: "dr11", text: "Slow dance with me to an imaginary song for 60 seconds.", type: "dare" },
        { id: "dr12", text: "Look into my eyes and say something you've never said before.", type: "dare" },
        { id: "dr13", text: "Whisper a sweet secret in my ear.", type: "dare" },
        { id: "dr14", text: "Hold me from behind and tell me how your day was", type: "dare" },
        { id: "dr15", text: "Write 'I love you' somewhere creative around the room", type: "dare" },
        { id: "dr16", text: "Describe your ideal morning with me in vivid detail", type: "dare" },
        { id: "dr17", text: "Trace a heart on my palm with your finger — slowly", type: "dare" },
        { id: "dr18", text: "Pick a star outside and name it after us", type: "dare" },
        { id: "dr19", text: "Play our song and sway together without talking", type: "dare" },
        { id: "dr20", text: "Read me a love quote and tell me why it reminds you of us", type: "dare" },
        { id: "dr21", text: "Place your hand over my heart and tell me something meaningful", type: "dare" },
        { id: "dr22", text: "Create a bucket list of 5 romantic things we must do together", type: "dare" },
        { id: "dr23", text: "Close your eyes and describe what my smile looks like from memory", type: "dare" },
        { id: "dr24", text: "Give me a hand kiss like they do in old romance movies", type: "dare" },
        { id: "dr25", text: "Tell me a fairy tale where we are the main characters", type: "dare" },
    ] as GameCard[],

    // ─── BOLD (Premium Only – 40 cards) ───
    bold: [
        { id: "tb1", text: "What's the most daring thing you'd want to try with me?", type: "truth", isPremium: true },
        { id: "tb2", text: "What's your biggest turn-on that I might not know about?", type: "truth", isPremium: true },
        { id: "tb3", text: "Have you ever had a dream about me? Describe the feeling.", type: "truth", isPremium: true },
        { id: "tb4", text: "What's the most attractive thing I do without trying?", type: "truth", isPremium: true },
        { id: "tb5", text: "If we had zero inhibitions for one evening, how would we spend it?", type: "truth", isPremium: true },
        { id: "tb6", text: "What part of my personality attracts you the most?", type: "truth", isPremium: true },
        { id: "tb7", text: "What's a fantasy date you'd plan with no budget?", type: "truth", isPremium: true },
        { id: "tb8", text: "What's the boldest compliment you've ever wanted to give me?", type: "truth", isPremium: true },
        { id: "tb9", text: "What's something we haven't done yet that you really want to?", type: "truth", isPremium: true },
        { id: "tb10", text: "If you could read my mind right now, what do you think I'm thinking?", type: "truth", isPremium: true },
        { id: "tb11", text: "What's something I do that gives you butterflies?", type: "truth", isPremium: true },
        { id: "tb12", text: "What's your favorite way I get your attention?", type: "truth", isPremium: true },
        { id: "tb13", text: "What's a bold thought you've had about us lately?", type: "truth", isPremium: true },
        { id: "tb14", text: "What's a look I give you that makes your heart race?", type: "truth", isPremium: true },
        { id: "tb15", text: "What's something I wear that you can't stop thinking about?", type: "truth", isPremium: true },
        { id: "tb16", text: "When do you feel the strongest connection between us?", type: "truth", isPremium: true },
        { id: "tb17", text: "What's a secret wish you have about us that feels daring?", type: "truth", isPremium: true },
        { id: "tb18", text: "What's the most electrifying moment we've shared?", type: "truth", isPremium: true },
        { id: "tb19", text: "What energy do I bring that no one else does?", type: "truth", isPremium: true },
        { id: "tb20", text: "If tonight had no rules, what would you want us to do first?", type: "truth", isPremium: true },
        { id: "db1", text: "Give me a 10-second shoulder massage 💆", type: "dare", isPremium: true },
        { id: "db2", text: "Whisper your boldest thought about me in my ear", type: "dare", isPremium: true },
        { id: "db3", text: "Do the most confident walk across the room while I watch 😏", type: "dare", isPremium: true },
        { id: "db4", text: "Look at me and describe what you see — be bold", type: "dare", isPremium: true },
        { id: "db5", text: "Say the flirtiest pickup line you can think of", type: "dare", isPremium: true },
        { id: "db6", text: "Text me the emoji that best describes how you feel right now", type: "dare", isPremium: true },
        { id: "db7", text: "Give me your most intense 5-second eye contact", type: "dare", isPremium: true },
        { id: "db8", text: "Hold my face and say the boldest thing on your mind", type: "dare", isPremium: true },
        { id: "db9", text: "Dance for me for 15 seconds — your choice of style", type: "dare", isPremium: true },
        { id: "db10", text: "Describe your ideal evening with me in one sentence", type: "dare", isPremium: true },
        { id: "db11", text: "Pull me closer and hold me for 30 slow seconds.", type: "dare", isPremium: true },
        { id: "db12", text: "Say something playful that would make me blush.", type: "dare", isPremium: true },
        { id: "db13", text: "Lean in close and pause… then smile without saying a word.", type: "dare", isPremium: true },
        { id: "db14", text: "Run your fingers through my hair while telling me something bold", type: "dare", isPremium: true },
        { id: "db15", text: "Stand behind me, put your arms around me, and say one word", type: "dare", isPremium: true },
        { id: "db16", text: "Give me a slow, dramatic compliment like a movie character", type: "dare", isPremium: true },
        { id: "db17", text: "Lower your voice and say something that only I should hear", type: "dare", isPremium: true },
        { id: "db18", text: "Pick a song, play it, and look at me like I'm the only person alive", type: "dare", isPremium: true },
        { id: "db19", text: "Touch my wrist gently and don't break eye contact for 10 seconds", type: "dare", isPremium: true },
        { id: "db20", text: "Describe in one sentence how it feels to be close to me right now", type: "dare", isPremium: true },
    ] as GameCard[],

    // ─── DEEP (50 cards) ───
    deep: [
        { id: "td1", text: "What's something about me that you silently admire?", type: "truth" },
        { id: "td2", text: "When did you know I was the one?", type: "truth" },
        { id: "td3", text: "What's a fear you have about our relationship?", type: "truth" },
        { id: "td4", text: "What's the hardest thing about loving someone deeply?", type: "truth" },
        { id: "td5", text: "What moment between us changed you as a person?", type: "truth" },
        { id: "td6", text: "What do you think makes us different from other couples?", type: "truth" },
        { id: "td7", text: "What's a sacrifice you've made for this relationship?", type: "truth" },
        { id: "td8", text: "If we had to overcome one challenge, what would it be?", type: "truth" },
        { id: "td9", text: "What's the most vulnerable you've ever felt with me?", type: "truth" },
        { id: "td10", text: "What lesson has loving me taught you?", type: "truth" },
        { id: "td11", text: "What's something you're afraid to lose in our relationship?", type: "truth" },
        { id: "td12", text: "What does emotional safety mean to you?", type: "truth" },
        { id: "td13", text: "How do you feel most supported by me?", type: "truth" },
        { id: "td14", text: "What's one way we've grown together?", type: "truth" },
        { id: "td15", text: "What does commitment mean to you?", type: "truth" },
        { id: "td16", text: "When do you feel most connected to me?", type: "truth" },
        { id: "td17", text: "What's something you want us to build together in the future?", type: "truth" },
        { id: "td18", text: "What's your biggest insecurity in love?", type: "truth" },
        { id: "td19", text: "What does forgiveness mean to you in a relationship?", type: "truth" },
        { id: "td20", text: "What's a truth you've been holding back because you're scared?", type: "truth" },
        { id: "td21", text: "How has our relationship changed who you are?", type: "truth" },
        { id: "td22", text: "What's the bravest thing you've done for love?", type: "truth" },
        { id: "td23", text: "What's a boundary you'd never want us to cross?", type: "truth" },
        { id: "td24", text: "What does being truly known by someone feel like?", type: "truth" },
        { id: "td25", text: "What part of your past do you think shaped how you love?", type: "truth" },
        { id: "dd1", text: "Tell me the thing you've been afraid to say", type: "dare" },
        { id: "dd2", text: "Write down one thing you promise to do better — and mean it", type: "dare" },
        { id: "dd3", text: "Call someone important to you and tell them how much they mean", type: "dare" },
        { id: "dd4", text: "Share a memory that changed your perspective on life", type: "dare" },
        { id: "dd5", text: "Look at me and apologize for something — even small", type: "dare" },
        { id: "dd6", text: "Tell me about a time you were proud of me", type: "dare" },
        { id: "dd7", text: "Describe where you see us in 5 years", type: "dare" },
        { id: "dd8", text: "Share one thing you've never told anyone else", type: "dare" },
        { id: "dd9", text: "Hold my hand and tell me what you're grateful for today", type: "dare" },
        { id: "dd10", text: "Write me a letter that starts with 'I want you to know...'", type: "dare" },
        { id: "dd11", text: "Tell me about a moment you almost gave up on something important", type: "dare" },
        { id: "dd12", text: "Close your eyes and describe how my love makes you feel", type: "dare" },
        { id: "dd13", text: "Name three things about yourself you're still learning to accept", type: "dare" },
        { id: "dd14", text: "Share one thing you hope I never stop doing", type: "dare" },
        { id: "dd15", text: "Tell me what you needed to hear as a child and never did", type: "dare" },
        { id: "dd16", text: "Describe the exact moment you felt most at home with me", type: "dare" },
        { id: "dd17", text: "Look at me and say what you'd want to tell me if this was our last day", type: "dare" },
        { id: "dd18", text: "Share a belief about love that you've completely changed over time", type: "dare" },
        { id: "dd19", text: "Write down one word that describes what I mean to you — and explain it", type: "dare" },
        { id: "dd20", text: "Whisper something healing to me that you also need to hear yourself", type: "dare" },
        { id: "dd21", text: "Tell me about the hardest goodbye you've ever said", type: "dare" },
        { id: "dd22", text: "Share a promise you want to make to our future selves", type: "dare" },
        { id: "dd23", text: "Describe what true loyalty means to you using our relationship as an example", type: "dare" },
        { id: "dd24", text: "Tell me one thing you want me to understand about how you love", type: "dare" },
        { id: "dd25", text: "Hold both my hands and tell me what you're most hopeful about", type: "dare" },
    ] as GameCard[],

    // ─── MIDNIGHT MOOD (Premium Only – 40 cards) ───
    // Intense. Magnetic. Slow-burn. Never explicit.
    midnightMood: [
        { id: "tmm1", text: "What's the most intense moment you've ever felt with me?", type: "truth", isPremium: true },
        { id: "tmm2", text: "When do you feel the strongest pull toward me?", type: "truth", isPremium: true },
        { id: "tmm3", text: "What part of our chemistry feels almost electric?", type: "truth", isPremium: true },
        { id: "tmm4", text: "Have you ever felt jealous of the attention I get? Be honest.", type: "truth", isPremium: true },
        { id: "tmm5", text: "What's the most powerful emotion you've felt when we were alone?", type: "truth", isPremium: true },
        { id: "tmm6", text: "What's something about me that keeps you up at night?", type: "truth", isPremium: true },
        { id: "tmm7", text: "When do you feel like I have all your attention without even trying?", type: "truth", isPremium: true },
        { id: "tmm8", text: "What's a moment between us that felt like time stopped?", type: "truth", isPremium: true },
        { id: "tmm9", text: "What's a side of me only you get to see?", type: "truth", isPremium: true },
        { id: "tmm10", text: "When do you feel the most magnetic energy between us?", type: "truth", isPremium: true },
        { id: "tmm11", text: "What's something I do that creates tension — the good kind?", type: "truth", isPremium: true },
        { id: "tmm12", text: "What's a word you'd use to describe us at our most intense?", type: "truth", isPremium: true },
        { id: "tmm13", text: "What's a moment where my presence alone was enough?", type: "truth", isPremium: true },
        { id: "tmm14", text: "What's something unspoken between us that we both feel?", type: "truth", isPremium: true },
        { id: "tmm15", text: "If our connection had a color, what would it be and why?", type: "truth", isPremium: true },
        { id: "tmm16", text: "What does 'wanting someone deeply' mean to you?", type: "truth", isPremium: true },
        { id: "tmm17", text: "What's a thought about us that feels almost too intense to say?", type: "truth", isPremium: true },
        { id: "tmm18", text: "When do you feel possessive about me — in a healthy way?", type: "truth", isPremium: true },
        { id: "tmm19", text: "What part of being with me feels addictive?", type: "truth", isPremium: true },
        { id: "tmm20", text: "What's a moment you wanted to pull me closer but held back?", type: "truth", isPremium: true },
        { id: "dmm1", text: "Stand close enough that there's barely space between us — hold it for 20 seconds.", type: "dare", isPremium: true },
        { id: "dmm2", text: "Look at me like you're about to say something dangerous… then smile instead.", type: "dare", isPremium: true },
        { id: "dmm3", text: "Hold my wrist gently and tell me what you admire about my strength.", type: "dare", isPremium: true },
        { id: "dmm4", text: "Say something intense — but meaningful — about how you feel for me.", type: "dare", isPremium: true },
        { id: "dmm5", text: "Whisper a promise about our future that feels bold.", type: "dare", isPremium: true },
        { id: "dmm6", text: "Put your hand on my chest and say one word that describes this moment.", type: "dare", isPremium: true },
        { id: "dmm7", text: "Lower the lights, hold my face, and tell me what I mean to you.", type: "dare", isPremium: true },
        { id: "dmm8", text: "Lock eyes with me and don't look away until I do.", type: "dare", isPremium: true },
        { id: "dmm9", text: "Walk toward me slowly, stop inches away, and say nothing for 10 seconds.", type: "dare", isPremium: true },
        { id: "dmm10", text: "Describe the energy in the room right now using only one sentence.", type: "dare", isPremium: true },
        { id: "dmm11", text: "Say my name like it's the only word that matters.", type: "dare", isPremium: true },
        { id: "dmm12", text: "Hold my hand tight and tell me something you've kept close to your heart.", type: "dare", isPremium: true },
        { id: "dmm13", text: "Look at me in silence for 15 seconds. Let whatever you feel just exist.", type: "dare", isPremium: true },
        { id: "dmm14", text: "Trace your finger along my palm while telling me your boldest wish for us.", type: "dare", isPremium: true },
        { id: "dmm15", text: "Turn off all the music. Look at me. Now say what's really on your mind.", type: "dare", isPremium: true },
        { id: "dmm16", text: "Lean your forehead against mine and breathe together for 30 seconds.", type: "dare", isPremium: true },
        { id: "dmm17", text: "Say something to me that you'd only say at midnight.", type: "dare", isPremium: true },
        { id: "dmm18", text: "Hold me from behind and whisper one word. Just one.", type: "dare", isPremium: true },
        { id: "dmm19", text: "Pick a slow song, press play, and just look at me while it plays.", type: "dare", isPremium: true },
        { id: "dmm20", text: "Close every gap between us and hold it — let the silence do the talking.", type: "dare", isPremium: true },
    ] as GameCard[],
};

// ──────────────────────────────────────────────
// 2. SPIN THE WHEEL (40 cards with categories)
// ──────────────────────────────────────────────

export const spinWheel: GameCard[] = [
    { id: "sw1", text: "Kiss each other's hand 💕", category: "surprise" },
    { id: "sw2", text: "Share your favorite meal memory together", category: "memory" },
    { id: "sw3", text: "Give a 30-second back rub", category: "mini-task" },
    { id: "sw4", text: "Look into each other's eyes for 1 minute", category: "mini-task" },
    { id: "sw5", text: "Name 5 things you love about the other person", category: "compliment" },
    { id: "sw6", text: "Recreate your first date scenario", category: "memory" },
    { id: "sw7", text: "Feed each other a snack blindfolded", category: "surprise" },
    { id: "sw8", text: "Do a couple pose and take a photo", category: "mini-task" },
    { id: "sw9", text: "Sing a love song to each other", category: "surprise" },
    { id: "sw10", text: "Slow dance for 1 minute", category: "mini-task" },
    { id: "sw11", text: "Write a haiku about your partner", category: "compliment" },
    { id: "sw12", text: "Plan a surprise date for this weekend", category: "surprise" },
    { id: "sw13", text: "Share a childhood story you've never told", category: "memory" },
    { id: "sw14", text: "Give each other new nicknames for the night", category: "tease" },
    { id: "sw15", text: "Describe your partner using only 3 words", category: "compliment" },
    { id: "sw16", text: "Trade phones for 2 minutes — look at photos only", category: "tease" },
    { id: "sw17", text: "Do a trust fall with your partner", category: "mini-task" },
    { id: "sw18", text: "Cook or order something new together tonight", category: "surprise" },
    { id: "sw19", text: "Give your partner a sincere compliment about their personality.", category: "compliment" },
    { id: "sw20", text: "Share your favorite shared memory in detail.", category: "memory" },
    { id: "sw21", text: "Send a playful look that says more than words.", category: "tease" },
    { id: "sw22", text: "Plan a mini surprise for later tonight.", category: "surprise" },
    { id: "sw23", text: "Sit closer than usual for the next two minutes.", category: "mini-task" },
    { id: "sw24", text: "Say one word that describes how you feel about them right now", category: "compliment" },
    { id: "sw25", text: "Tell a story about the first time they made you laugh", category: "memory" },
    { id: "sw26", text: "Mimic their laugh — make it as accurate as possible", category: "tease" },
    { id: "sw27", text: "Hide a sweet note somewhere they'll find tomorrow", category: "surprise" },
    { id: "sw28", text: "Hold each other's hands for 2 minutes while sharing something kind", category: "mini-task" },
    { id: "sw29", text: "Tell them the best compliment you've ever received about your relationship", category: "compliment" },
    { id: "sw30", text: "Share the moment you knew this was real", category: "memory" },
    { id: "sw31", text: "Wink at your partner like they're a stranger across the room", category: "tease" },
    { id: "sw32", text: "Swap a clothing item with your partner for 10 minutes", category: "surprise" },
    { id: "sw33", text: "Teach your partner your favorite dance move", category: "mini-task" },
    { id: "sw34", text: "Describe their smile without using the word 'smile'", category: "compliment" },
    { id: "sw35", text: "Tell them about a time you bragged about them to someone", category: "memory" },
    { id: "sw36", text: "Speak in an accent for the next 2 minutes", category: "tease" },
    { id: "sw37", text: "Set a new wallpaper on your phone — a photo of you two", category: "surprise" },
    { id: "sw38", text: "Create a 10-second couple dance routine right now", category: "mini-task" },
    { id: "sw39", text: "Use only your eyes to say 'I love you'", category: "tease" },
    { id: "sw40", text: "Tell them one thing about them you'd never want to change", category: "compliment" },
];

// ──────────────────────────────────────────────
// 3. SCRATCH & REVEAL (40 cards)
// ──────────────────────────────────────────────

export const scratchReveal: GameCard[] = [
    { id: "sr1", text: "🌹 Plan a candlelit dinner at home this week" },
    { id: "sr2", text: "💌 Write a love letter and hide it somewhere for them to find" },
    { id: "sr3", text: "🎵 Create a playlist of songs that remind you of your partner" },
    { id: "sr4", text: "📸 Take a spontaneous photo walk together" },
    { id: "sr5", text: "🍳 Breakfast in bed surprise this weekend" },
    { id: "sr6", text: "✨ Give each other a new compliment every hour today" },
    { id: "sr7", text: "🎁 Plan a surprise gift — budget under $10" },
    { id: "sr8", text: "🌙 Stargaze together tonight (or cloud watch)" },
    { id: "sr9", text: "📝 Write 3 things you admire about each other" },
    { id: "sr10", text: "🎬 Watch each other's favorite childhood movie tonight" },
    { id: "sr11", text: "💃 Learn a simple couple dance from YouTube" },
    { id: "sr12", text: "🧘 Do a 10-minute meditation together" },
    { id: "sr13", text: "🍰 Bake or make something sweet together" },
    { id: "sr14", text: "🖼️ Frame a photo of you two and display it" },
    { id: "sr15", text: "📖 Read to each other for 15 minutes" },
    { id: "sr16", text: "🎨 Draw portraits of each other — no peeking!" },
    { id: "sr17", text: "🌅 Wake up early and watch the sunrise together" },
    { id: "sr18", text: "💐 Pick or buy a flower for your partner" },
    { id: "sr19", text: "🎯 Set a couples goal together for this month" },
    { id: "sr20", text: "🎤 Karaoke night — sing love songs to each other" },
    { id: "sr21", text: "🔮 Tonight, you plan the next date — keep it mysterious." },
    { id: "sr22", text: "💭 Share one dream you've never told me about." },
    { id: "sr23", text: "💝 Give me a compliment that feels almost unfairly sweet." },
    { id: "sr24", text: "👀 For the next minute, only communicate through eye contact." },
    { id: "sr25", text: "🎬 Recreate your favorite romantic movie moment together." },
    { id: "sr26", text: "🧳 Plan a surprise weekend trip — even if it's just a plan" },
    { id: "sr27", text: "🫂 Give each other the longest, warmest hug you can" },
    { id: "sr28", text: "🖊️ Write down your favorite thing about each season with your partner" },
    { id: "sr29", text: "🍕 Order each other's favorite food as a surprise tonight" },
    { id: "sr30", text: "🎧 Listen to a song together with shared earphones — no talking" },
    { id: "sr31", text: "🧩 Start a puzzle together and finish it this week" },
    { id: "sr32", text: "🌻 Plant a small flower or herb together — name it after your relationship" },
    { id: "sr33", text: "📮 Send each other a handwritten note — even if you live together" },
    { id: "sr34", text: "🎭 Act out your favorite couple memory like a scene in a play" },
    { id: "sr35", text: "⏰ Set an alarm to say 'I love you' at a random time tomorrow" },
    { id: "sr36", text: "📷 Take 10 photos of each other doing everyday things — keep the best one" },
    { id: "sr37", text: "🛁 Run a warm bath or make a hot drink for your partner" },
    { id: "sr38", text: "🌈 Write a mini gratitude list about your partner — 10 things" },
    { id: "sr39", text: "📱 Change your partner's contact name to something really sweet" },
    { id: "sr40", text: "🎶 Dedicate a song to each other and explain why you chose it" },
];

// ──────────────────────────────────────────────
// 4. DEEP TALK (50 cards)
// ──────────────────────────────────────────────

export const deepTalk: GameCard[] = [
    { id: "dt1", text: "What does unconditional love mean to you?" },
    { id: "dt2", text: "What's a childhood memory that shaped who you are today?" },
    { id: "dt3", text: "What's the hardest decision you've ever had to make?" },
    { id: "dt4", text: "If money didn't exist, how would you spend your life?" },
    { id: "dt5", text: "What does a perfect day look like for you?" },
    { id: "dt6", text: "What's something most people misunderstand about you?" },
    { id: "dt7", text: "What are you most proud of in your life?" },
    { id: "dt8", text: "What scares you the most about the future?" },
    { id: "dt9", text: "What role does forgiveness play in your life?" },
    { id: "dt10", text: "What's a belief you held strongly but later changed?" },
    { id: "dt11", text: "What does vulnerability mean to you in a relationship?" },
    { id: "dt12", text: "What's one thing you wish you could tell your younger self?" },
    { id: "dt13", text: "What makes you feel most alive?" },
    { id: "dt14", text: "What's a moment where you felt truly at peace?" },
    { id: "dt15", text: "What does commitment in a relationship look like for you?" },
    { id: "dt16", text: "How do you handle conflict, and how do you wish you handled it?" },
    { id: "dt17", text: "What legacy do you want to leave behind?" },
    { id: "dt18", text: "What's the kindest thing someone has ever done for you?" },
    { id: "dt19", text: "What does home mean to you?" },
    { id: "dt20", text: "What are your top 3 values in life?" },
    { id: "dt21", text: "What's a dream you've never told anyone about?" },
    { id: "dt22", text: "How do you want to grow as a person this year?" },
    { id: "dt23", text: "What does success mean in a relationship?" },
    { id: "dt24", text: "What's the best piece of advice you've ever received?" },
    { id: "dt25", text: "If you could change one thing about the world, what would it be?" },
    { id: "dt26", text: "What's a moment in your life that completely changed your direction?" },
    { id: "dt27", text: "How do you define trust, and how is it earned?" },
    { id: "dt28", text: "What's one thing you want your partner to always remember about you?" },
    { id: "dt29", text: "What does growing old together look like in your mind?" },
    { id: "dt30", text: "What's a lesson love has taught you that nothing else could?" },
    { id: "dt31", text: "What's a conversation you've been avoiding because it feels too real?" },
    { id: "dt32", text: "What does emotional intelligence mean to you?" },
    { id: "dt33", text: "What's the most selfless thing someone has done for you?" },
    { id: "dt34", text: "What does loyalty look like in a world full of options?" },
    { id: "dt35", text: "What's a part of yourself you're still figuring out?" },
    { id: "dt36", text: "What would you want people to say about you at your wedding?" },
    { id: "dt37", text: "What's a question you're afraid to know the answer to?" },
    { id: "dt38", text: "When was the last time you cried, and what triggered it?" },
    { id: "dt39", text: "What does it mean to be truly heard by someone?" },
    { id: "dt40", text: "What's the difference between being alone and being lonely?" },
    { id: "dt41", text: "What's a hard truth about love that most people avoid?" },
    { id: "dt42", text: "What's the most important thing you've learned about yourself this year?" },
    { id: "dt43", text: "How do you recharge after an emotionally draining day?" },
    { id: "dt44", text: "What does healthy communication look like to you?" },
    { id: "dt45", text: "What's a wound from your past that still affects how you love today?" },
    { id: "dt46", text: "What's a moment you realized you were stronger than you thought?" },
    { id: "dt47", text: "What does an ideal apology look and sound like?" },
    { id: "dt48", text: "What's a non-negotiable value in your relationships?" },
    { id: "dt49", text: "If you could have a deep conversation with anyone dead or alive, who?" },
    { id: "dt50", text: "What does being at peace with yourself actually feel like?" },
];

// ──────────────────────────────────────────────
// 5. 5-MINUTE CHALLENGE (35 cards)
// ──────────────────────────────────────────────

export const fiveMinChallenge: GameCard[] = [
    { id: "fc1", text: "Name as many things you love about each other as you can in 5 minutes!" },
    { id: "fc2", text: "Plan your dream vacation together — destination, activities, everything — in 5 minutes!" },
    { id: "fc3", text: "Take turns complimenting each other without repeating — who runs out first?" },
    { id: "fc4", text: "Tell each other your favorite memories together — alternate, don't repeat!" },
    { id: "fc5", text: "5-minute question round: ask each other anything, must answer honestly!" },
    { id: "fc6", text: "Build a bucket list together — as many items as possible in 5 minutes!" },
    { id: "fc7", text: "Describe each other to a stranger — how would you introduce your partner?" },
    { id: "fc8", text: "Write a short love story about yourselves in 5 minutes — then read it aloud!" },
    { id: "fc9", text: "Speed round: say the first word that comes to mind about your partner!" },
    { id: "fc10", text: "Plan a surprise party for each other — theme, food, guests — in 5 minutes!" },
    { id: "fc11", text: "Name songs that remind you of each other — alternate, don't repeat!" },
    { id: "fc12", text: "Create couple resolutions for this month — realistic ones only!" },
    { id: "fc13", text: "Act out how you first met — dramatic movie version!" },
    { id: "fc14", text: "Give each other a rapid-fire confidence boost — 1 compliment every 10 seconds!" },
    { id: "fc15", text: "Debate: who fell in love first? Defend your side!" },
    { id: "fc16", text: "Maintain eye contact for one full minute without laughing." },
    { id: "fc17", text: "Take turns saying things you appreciate about each other for 2 minutes." },
    { id: "fc18", text: "Sit in silence holding hands for 3 minutes." },
    { id: "fc19", text: "Share a future goal and how you want to achieve it together." },
    { id: "fc20", text: "Create a secret code word only the two of you understand." },
    { id: "fc21", text: "List 10 reasons you're grateful for your relationship — no pausing!" },
    { id: "fc22", text: "Take turns finishing this sentence: 'I love us because...' — don't repeat!" },
    { id: "fc23", text: "Describe your perfect weekend together in every detail — 5 minutes go!" },
    { id: "fc24", text: "Rapid fire: say the first memory that comes to mind about each other!" },
    { id: "fc25", text: "Plan your dream home together — rooms, decor, neighborhood — go!" },
    { id: "fc26", text: "Give each other a new pet name every 30 seconds for 3 minutes!" },
    { id: "fc27", text: "Name all the inside jokes you have — how many can you remember?" },
    { id: "fc28", text: "Roleplay: you just met at a coffee shop. Introduce yourselves!" },
    { id: "fc29", text: "Take turns finishing: 'One thing I'll never forget about you is...'!" },
    { id: "fc30", text: "Speed plan: organize a surprise for your partner's next birthday — 5 minutes!" },
    { id: "fc31", text: "Mirror challenge: copy each other's movements for 2 minutes!" },
    { id: "fc32", text: "Tell each other 5 things you'd save in a fire (besides people and pets)!" },
    { id: "fc33", text: "Take turns asking 'would you rather' questions — romantic edition!" },
    { id: "fc34", text: "Describe your relationship using only song titles — alternate turns!" },
    { id: "fc35", text: "Two-minute appreciation avalanche: non-stop kind words without pausing!" },
];

// ──────────────────────────────────────────────
// 6. EMOTIONAL BOND (40 cards)
// ──────────────────────────────────────────────

export const emotionalBond: GameCard[] = [
    { id: "eb1", text: "What's something I do that makes you feel safe?" },
    { id: "eb2", text: "When did you feel most supported by me?" },
    { id: "eb3", text: "What's a fear you've never shared fully?" },
    { id: "eb4", text: "What does forever mean to you?" },
    { id: "eb5", text: "What's one insecurity you wish I understood better?" },
    { id: "eb6", text: "How can I love you better?" },
    { id: "eb7", text: "What kind of future do you see when you picture us?" },
    { id: "eb8", text: "What part of yourself do you feel safest showing me?" },
    { id: "eb9", text: "When have you felt most proud of us?" },
    { id: "eb10", text: "What promise matters most in a relationship?" },
    { id: "eb11", text: "What's the most healing thing I've ever said to you?" },
    { id: "eb12", text: "When do you feel the most emotionally close to me?" },
    { id: "eb13", text: "What's a moment where I made you feel truly seen?" },
    { id: "eb14", text: "What does being emotionally held look like for you?" },
    { id: "eb15", text: "What's something about your inner world you want me to know?" },
    { id: "eb16", text: "What's a need you have in love that you rarely express?" },
    { id: "eb17", text: "What does trust feel like in your body?" },
    { id: "eb18", text: "How do you know when someone truly loves you?" },
    { id: "eb19", text: "What's a wound you carry that I can help heal?" },
    { id: "eb20", text: "What does it mean to belong to someone emotionally?" },
    { id: "eb21", text: "When do you feel most like yourself around me?" },
    { id: "eb22", text: "What's a feeling you've struggled to put into words for me?" },
    { id: "eb23", text: "What's the quietest way I show you love?" },
    { id: "eb24", text: "When do you need me the most and how can I notice?" },
    { id: "eb25", text: "What would an emotionally perfect day together look like?" },
    { id: "eb26", text: "What's a part of our bond you never want to lose?" },
    { id: "eb27", text: "What's something I said once that you still carry with you?" },
    { id: "eb28", text: "When do you feel most understood by me?" },
    { id: "eb29", text: "What's an emotional risk you took for me that I might not know about?" },
    { id: "eb30", text: "How do you define emotional intimacy?" },
    { id: "eb31", text: "What makes our bond different from any other you've had?" },
    { id: "eb32", text: "What's a silent way you check on me when I seem off?" },
    { id: "eb33", text: "When do you feel most protective of our relationship?" },
    { id: "eb34", text: "What's a boundary that actually brought us closer?" },
    { id: "eb35", text: "What's the bravest emotional thing you've ever done for love?" },
    { id: "eb36", text: "What do you hope I always feel when I'm with you?" },
    { id: "eb37", text: "What's a moment where we grew through something hard together?" },
    { id: "eb38", text: "How do you want to be comforted when the world feels heavy?" },
    { id: "eb39", text: "What's one thing about the way we love that you're proud of?" },
    { id: "eb40", text: "If our relationship had a safe word that means 'I need you right now', what would it be?" },
];

// ──────────────────────────────────────────────
// MASTER CONTENT OBJECT
// ──────────────────────────────────────────────

export const gameContent = {
    truthOrDare,
    spinWheel,
    scratchReveal,
    deepTalk,
    fiveMinChallenge,
    emotionalBond,
};

// Utility: shuffle array (Fisher-Yates)
export function shuffleArray<T>(array: T[]): T[] {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

// Utility: get random items from array
export function getRandomItems<T>(array: T[], count: number): T[] {
    return shuffleArray(array).slice(0, count);
}

// Available game modes (for validation)
export const GAME_MODES = [
    "truth-or-dare",
    "spin-wheel",
    "scratch-reveal",
    "deep-talk",
    "challenge",
    "emotional-bond",
] as const;

export type GameMode = (typeof GAME_MODES)[number];

// Free user daily play limit
export const FREE_DAILY_LIMIT = 3;
